import {getPublicData} from '@/lib/public-data';
import {CompetitionSelector, ContextLabel, SourceStatus} from '@/components/public/competition';
import {StatsTable} from '@/components/public/statistics';
import {Metric, Page, SectionHeading} from '@/components/public/ui';
import {numberNL} from '@/components/public/format';
export const dynamic = 'force-dynamic';
export const metadata = {title: 'Statistieken', description: 'Officiële NSJL X01- en Cricket-statistieken binnen de juiste team- en seizoencontext.', alternates: {canonical: '/statistieken'}};
export default async function Statistics({searchParams}: {searchParams: Promise<{context?: string}>}) {
  const data = await getPublicData((await searchParams).context);
  return <Page><SectionHeading as="h1" title="Statistieken" intro="De cijfers achter het geluk. Altijd met de juiste context."/><CompetitionSelector data={data} path="/statistieken"/><ContextLabel data={data}/><dl className="pub-team-metrics"><Metric label="Gespeelde legs" value={numberNL(data.nsjl?.games, 0)}/><Metric label="Gewonnen legs" value={numberNL(data.nsjl?.wins, 0)}/><Metric label="Verloren legs" value={numberNL(data.nsjl?.losses, 0)}/><Metric label="Winpercentage legs" value={data.nsjl?.winPercentage != null ? numberNL(data.nsjl.winPercentage, 1) + '%' : '—'}/></dl><nav className="pub-filter-bar" aria-label="Statistiekonderdelen"><a href="#x01">X01</a><a href="#cricket">Cricket</a></nav><section id="x01"><SectionHeading title="X01" intro="PPD en de beschikbare prestaties per speler. Gesorteerd op PPD."/><StatsTable data={data} game="x01"/>{data.stats.length > 0 && <details className="pub-stats-details"><summary>Alle X01-prestaties, inclusief 6–15 darts outs</summary><StatsTable data={data} game="x01" advanced/></details>}</section><section id="cricket" className="pub-section"><SectionHeading title="Cricket" intro="MPR, gewonnen games en de beschikbare Cricket-prestaties. Gesorteerd op MPR."/><StatsTable data={data} game="cricket"/>{data.stats.length > 0 && <details className="pub-stats-details"><summary>Alle Cricket-prestaties, inclusief 5–9 marks rounds</summary><StatsTable data={data} game="cricket" advanced/></details>}</section><SourceStatus data={data}/><p className="pub-notice">Alle spelerscijfers horen bij NSJL in de geselecteerde competitie, divisie en seizoen. PPD en MPR worden niet ongewogen gemiddeld. Onbekend is “—”, geen nul. Onbevestigde legacy-cijfers tellen hier niet mee.</p></Page>;
}
