import Link from 'next/link';
import {notFound} from 'next/navigation';
import {AdminForm} from '@/components/admin-form';
import {readEnv} from '@/lib/env';
import {requireAdmin} from '@/lib/auth';
import {getAdminData} from '@/lib/queries';
import {adminSections,SyncButton} from '@/components/admin-shell';
import {PlayerEditor,NewsEditor,EventEditor,SponsorEditor,CorrectionForm,EditForm,Field,TextField} from '@/components/admin-editors';
import {RecordActions} from '@/components/admin-record-actions';
import {recordRevision} from '@/lib/admin/record-guard';
import {StandTable,MatchCard,SourceNote} from '@/components/data-ui';
export const dynamic='force-dynamic';
export default async function AdminSection({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{message?:string}>}){
  await requireAdmin();const {section}=await params,title=adminSections.find(s=>s.slug===section)?.label;if(!title)notFound();const d=await getAdminData(),{message}=await searchParams;
  return <><div className="page-heading"><div><span className="eyebrow">NSJL beheer</span><h1>{title}</h1></div>{section==='synchronisatie'&&<SyncButton/>}</div>{message&&<p className="notice" role="status">{message}</p>}
    {section==='synchronisatie'&&<><SourceNote data={d.site}/><div className="card"><h2>Bronconfiguratie</h2><p className="notice">Synchronisatie en bronactivering blijven geblokkeerd zolang SYNC_ENABLED=false. Deze fase voert geen import uit.</p>{d.configs.map(c=><div key={c.id}><p><strong>{c.expectedLeagueCode}</strong> · automatische sync {c.enabled?'aan':'uit'}</p><p className="muted">Iedere synchronisatie ontdekt opnieuw de report-URL. Er worden geen vaste reportbestanden gebruikt.</p><EditForm resource="bronconfiguratie" id={c.id} disabled={!readEnv().SYNC_ENABLED}><label><input type="checkbox" name="enabled" defaultChecked={c.enabled} disabled={!readEnv().SYNC_ENABLED}/> Automatisch synchroniseren (ook SYNC_ENABLED vereist)</label></EditForm></div>)}</div><h2>Synchronisatielog</h2><div className="stack">{d.runs.map(r=><article className="card" key={r.id}><strong>{r.status} · {r.triggerType}</strong><p>{r.startedAt.toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'})}</p><p>Gevonden {r.recordsFound} · nieuw {r.recordsCreated} · bijgewerkt {r.recordsUpdated} · overgeslagen {r.recordsSkipped}</p>{r.errorMessage&&<p className="notice">{r.errorCode}: {r.errorMessage}</p>}</article>)}</div></>}
    {section==='spelers'&&<><Link className="button small" href="/admin/spelers/koppelingen">Bronspelers koppelen</Link><details className="card"><summary>Nieuw profiel</summary><PlayerEditor media={d.media}/></details><div className="stack">{d.allPlayers.map(p=><details className="card" key={p.id}><summary>{p.displayName} {p.isActive?'':'(gearchiveerd)'}</summary><PlayerEditor player={p} media={d.media}/><RecordActions resource="spelers" id={p.id} name={p.displayName} revision={recordRevision(p)} archived={!p.isActive}/></details>)}</div><div className="card"><h2>Afzonderlijke legacy-statistieken</h2><p>Deze oorspronkelijke profielcijfers zijn niet bewezen als officiële Bullshooter-data en worden niet gebruikt in competitie-statistieken.</p>{d.legacy.map(l=><p key={l.stats.id}>{l.name} · PPD {l.stats.ppd} · MPR {l.stats.mpr} · {l.stats.verificationStatus}</p>)}</div></>}
    {section==='wedstrijden'&&<><div className="card"><h2>Handmatige correctie</h2><p className="notice">Brongegevens blijven intact. Correcties vormen een afzonderlijke laag en vereisen een reden.</p><CorrectionForm resource="wedstrijden" targets={d.site.matches.map(m=>({id:m.id,name:`${m.scheduledDate} · ${m.homeName} – ${m.awayName}`}))} fields={['scheduledDate','startTime','status','notes','homeScore','awayScore'].map(value=>({value,name:value}))}/></div><div className="match-list">{d.site.matches.map(m=><MatchCard key={m.id} match={m}/>)}</div></>}
    {section==='stand'&&<><StandTable data={d.site}/><div className="card"><h2>Correctie met reden</h2><CorrectionForm resource="stand" targets={d.site.standings.map(t=>({id:t.teamSeasonId,name:t.name}))} fields={['position','wins','games'].map(value=>({value,name:value}))}/></div></>}
    {section==='statistieken'&&<><SourceNote data={d.site}/><div className="card"><h2>NSJL-statistieken in {d.site.context.season}</h2>{d.site.stats.map(p=><p key={p.stats.id}>{p.externalName} · PPD {p.stats.x01Ppd??'—'} · MPR {p.stats.cricketMpr??'—'}</p>)}<CorrectionForm resource="statistieken" targets={d.site.stats.map(p=>({id:p.stats.id,name:p.externalName}))} fields={[{value:'x01Ppd',name:'X01 PPD'},{value:'cricketMpr',name:'Cricket MPR'}]}/></div></>}
    {section==='nieuws'&&<><details className="card"><summary>Nieuw bericht</summary><NewsEditor media={d.media}/></details><div className="stack">{d.posts.map(p=><details className="card" key={p.id}><summary>{p.title} · {p.status}</summary><NewsEditor post={p} media={d.media}/><RecordActions resource="nieuws" id={p.id} name={p.title} revision={recordRevision(p)} archived={p.status==='archived'}/></details>)}</div></>}
    {section==='agenda'&&<><details className="card"><summary>Nieuw agenda-item</summary><EventEditor/></details><div className="stack">{d.events.map(e=><details className="card" key={e.id}><summary>{e.title} · {e.startsAt.toLocaleDateString('nl-NL')}{e.isActive?'':' (gearchiveerd)'}</summary><EventEditor event={e}/><RecordActions resource="agenda" id={e.id} name={e.title} revision={recordRevision(e)} archived={!e.isActive}/></details>)}</div></>}
    {section==='sponsors'&&<><details className="card"><summary>Nieuwe sponsor</summary><SponsorEditor media={d.media}/></details><div className="stack">{d.sponsors.map(s=><details className="card" key={s.id}><summary>{s.name}{s.isActive?'':' (gearchiveerd)'}</summary><SponsorEditor sponsor={s} media={d.media}/><RecordActions resource="sponsors" id={s.id} name={s.name} revision={recordRevision(s)} archived={!s.isActive}/></details>)}</div></>}
    {section==='media'&&<><div className="card"><h2>Afbeelding uploaden</h2><AdminForm action="/api/admin/media/upload" multipart><label>JPEG, PNG of WebP · maximaal 4 MiB<input type="file" name="file" accept="image/jpeg,image/png,image/webp" required/></label><Field name="altText" label="Beschrijving voor toegankelijkheid" required/><button className="button small">Privé uploaden</button></AdminForm><p className="muted">Uploads starten privé. Publicatie loopt via een gecontroleerde NSJL-link; het originele bestand blijft privé.</p></div><div className="stack">{d.media.map(m=><article className="card" key={m.id}><h2>{m.filename}</h2><p>{m.width} × {m.height} · {m.status}</p><a className="text-link" href={`/api/admin/media/${m.id}`} target="_blank" rel="noopener noreferrer">Afbeelding bekijken (nieuw tabblad)</a><EditForm resource="media" id={m.id}><TextField name="altText" label="Beschrijving" value={m.altText}/><label>Status<select name="status" defaultValue={m.status}><option value="private">Privé</option><option value="published">Publiceren</option><option value="archived">Archiveren</option></select></label></EditForm></article>)}</div></>}
    {section==='audit'&&<><p className="notice">Laatste 100 beheeracties. Dit log is alleen leesbaar; wijzigen en verwijderen worden door de database geweigerd. Tokens, codes en inhoud worden niet gelogd.</p><div className="stack">{d.audit.length?d.audit.map(a=><article className="card" key={a.id}><h2>{a.action}</h2><p><time dateTime={a.occurredAt.toISOString()}>{a.occurredAt.toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'})}</time> · {d.allUsers.find(u=>u.id===a.actorUserId)?.name||'Systeem'}</p><p>{a.summary}</p><small className="muted">{a.entityType}{a.entityId?' · '+a.entityId:''}</small></article>):<p className="notice">Nog geen beheeracties vastgelegd.</p>}</div></>}
    {section==='instellingen'&&<><div className="card"><h2>Alle beheeronderdelen</h2><div className="quick-links">{adminSections.map(s=><Link key={s.slug} href={`/admin/${s.slug}`}>{s.label}</Link>)}</div></div><div className="stack">{d.settings.filter(s=>['contact_email','home_venue','hero_subtitle'].includes(s.key)).map(s=><article key={s.key} className="card"><EditForm resource="instellingen"><input type="hidden" name="key" value={s.key}/><Field name="valueText" label={{contact_email:'Contact-e-mailadres',home_venue:'Thuislocatie',hero_subtitle:'Hero-intro'}[s.key]||s.key} value={s.valueText}/></EditForm></article>)}</div><div className="card"><h2>Jouw account</h2><Link className="text-link" href="/admin/wachtwoord">Wachtwoord wijzigen</Link><AdminForm action="/api/auth/logout"><button className="button secondary small">Uitloggen</button></AdminForm></div><div className="card"><h2>Beheerders</h2>{d.allUsers.map(u=><p key={u.id}>{u.name} · {u.role} · {u.isActive?'actief':'inactief'}</p>)}<p>Nieuwe beheerders worden uitsluitend via een veilige invite aangemaakt. De instructies staan in de opleverdocumentatie.</p></div></>}
  </>;
}
