import {describe,it,expect,beforeAll,afterAll} from 'vitest';
import {eq,and} from 'drizzle-orm';
import {testDatabase} from './database';
import {fixtureBundle} from './fixtures';
import {adminMutation} from '@/lib/admin/mutations';
import {enforceRateLimit} from '@/lib/rate-limit';
import {applyOverrides} from '@/lib/overrides';
import {prepareImage} from '@/lib/media';
import sharp from 'sharp';
import * as s from '@/db/schema';
import {synchronize} from '@/lib/sync/service';
let c:Awaited<ReturnType<typeof testDatabase>>,actor:string;
beforeAll(async()=>{c=await testDatabase();actor=crypto.randomUUID();await c.db.insert(s.users).values({id:actor,name:'Test admin',email:'admin@example.invalid'});const [source]=await c.db.select().from(s.sourceConfigs);await synchronize(c.db,source.id,{fetchBundle:async()=>fixtureBundle()},{trigger:'manual',cooldownMs:0});});
afterAll(async()=>{await c?.client.close();});
describe('Transactional administration',()=>{
  it('sanitizes saved news and archives without deletion',async()=>{await adminMutation(c.db,actor,'nieuws',{title:'Veilig nieuws',excerpt:'Test',content:'<p>Hallo</p><script>alert(1)</script><a href="javascript:alert(1)">link</a>',category:'Team',status:'published'});const [n]=await c.db.select().from(s.newsPosts).where(eq(s.newsPosts.slug,'veilig-nieuws'));expect(n.content).not.toMatch(/script|javascript|alert/);expect(n.authorId).toBe(actor);await adminMutation(c.db,actor,'nieuws',{action:'archive',id:n.id});expect((await c.db.select().from(s.newsPosts).where(eq(s.newsPosts.id,n.id)))[0].status).toBe('archived');expect((await c.db.select().from(s.auditLogs)).length).toBeGreaterThan(1);});
  it('explicit Tim link creates only the Bullshooter Saloon membership',async()=>{const [tim]=await c.db.select().from(s.players).where(eq(s.players.slug,'tim-goossens'));const [external]=await c.db.select().from(s.externalPlayers).where(eq(s.externalPlayers.normalizedName,'tim goossens'));await adminMutation(c.db,actor,'koppelingen',{externalId:external.id,playerId:tim.id});const memberships=await c.db.select().from(s.playerTeamSeasons).where(eq(s.playerTeamSeasons.playerId,tim.id));expect(memberships).toHaveLength(1);expect(memberships[0].teamSeasonId).toBe(external.teamSeasonId);const [nsjl]=await c.db.select().from(s.teamSeasons).where(eq(s.teamSeasons.isPrimaryNsjl,true));expect(memberships[0].teamSeasonId).not.toBe(nsjl.id);expect(await c.db.select().from(s.playerSeasonStats).where(and(eq(s.playerSeasonStats.playerId,tim.id),eq(s.playerSeasonStats.teamSeasonId,nsjl.id)))).toHaveLength(0);});
  it('conflicting player link rolls back membership and audit mutation',async()=>{const [external]=await c.db.select().from(s.externalPlayers).where(eq(s.externalPlayers.normalizedName,'tim goossens'));const [mike]=await c.db.select().from(s.players).where(eq(s.players.slug,'mike-van-de-voort'));await expect(adminMutation(c.db,actor,'koppelingen',{externalId:external.id,playerId:mike.id})).rejects.toThrow();expect(await c.db.select().from(s.playerTeamSeasons).where(and(eq(s.playerTeamSeasons.playerId,mike.id),eq(s.playerTeamSeasons.teamSeasonId,external.teamSeasonId)))).toHaveLength(0);});
  it('override layers preserve source values and replace the previous correction',async()=>{const [row]=await c.db.select().from(s.standings);for(const value of ['9','10'])await adminMutation(c.db,actor,'stand',{targetId:row.teamSeasonId,fieldName:'wins',value,reason:'Broncorrectie getest'});const original=(await c.db.select().from(s.standings).where(eq(s.standings.id,row.id)))[0];expect(original.wins).toBe(row.wins);const overrides=await c.db.select().from(s.dataOverrides).where(eq(s.dataOverrides.teamSeasonId,row.teamSeasonId));expect(overrides.filter(o=>o.isActive)).toHaveLength(1);expect(applyOverrides(original,overrides).wins).toBe(10);await expect(adminMutation(c.db,actor,'stand',{targetId:row.teamSeasonId,fieldName:'id',value:'123',reason:'Invalid test'})).rejects.toThrow();});
  it('agenda is reversibly archived; invalid dates fail atomically',async()=>{await adminMutation(c.db,actor,'agenda',{title:'Teamavond',startsAt:'2026-11-01T20:00:00+01:00',eventType:'team_event'});const [event]=await c.db.select().from(s.events).where(eq(s.events.title,'Teamavond'));await adminMutation(c.db,actor,'agenda',{id:event.id,action:'archive'});expect((await c.db.select().from(s.events).where(eq(s.events.id,event.id)))[0].isActive).toBe(false);await expect(adminMutation(c.db,actor,'agenda',{title:'Fout',startsAt:'bad',eventType:'team_event'})).rejects.toThrow();});
  it('rate limiting is shared and enforced by actual SQL',async()=>{await enforceRateLimit(c.db,'test','identity',2,60);await enforceRateLimit(c.db,'test','identity',2,60);await expect(enforceRateLimit(c.db,'test','identity',2,60)).rejects.toThrow('Te veel');});
});
describe('Image validation',()=>{
  it('rejects HTML, SVG, empty and oversized content',async()=>{for(const input of [Buffer.from('<html>not image</html>'),Buffer.from('<svg></svg>'),Buffer.alloc(0),Buffer.alloc(8*1024*1024+1)])await expect(prepareImage(input)).rejects.toThrow();});
  it('re-encodes decoded PNG into a metadata-free bounded WebP',async()=>{const input=await sharp({create:{width:32,height:16,channels:3,background:'#b9f553'}}).png().toBuffer();const output=await prepareImage(input);expect(output.info.format).toBe('webp');expect(output.info.width).toBe(32);const meta=await sharp(output.data).metadata();expect(meta.exif).toBeUndefined();});
});
