import {beforeAll,afterAll,beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {eq} from 'drizzle-orm';
import sharp from 'sharp';
import {testDatabase} from './database';
import * as s from '@/db/schema';
const storage=vi.hoisted(()=>({from:vi.fn()}));
vi.mock('@supabase/supabase-js',()=>({createClient:()=>({storage})}));
import {uploadMedia,changeMedia,prepareImage,safeImageFilename} from '@/lib/media';
let c:Awaited<ReturnType<typeof testDatabase>>,actor:string,image:Buffer;
const objects=new Map<string,Buffer>();
const writes=vi.fn(),removes=vi.fn();
function bucket(name:string){return {
  upload:async(path:string,body:Buffer|ArrayBuffer,options:{upsert:boolean;contentType:string})=>{writes(name,path,options);const key=`${name}/${path}`;if(objects.has(key)&&!options.upsert)return {error:{message:'exists'}};objects.set(key,body instanceof ArrayBuffer?Buffer.from(body):Buffer.from(body));return {error:null};},
  download:async(path:string)=>{const bytes=objects.get(`${name}/${path}`);return bytes?{data:new Blob([new Uint8Array(bytes)]),error:null}:{data:null,error:{message:'missing'}};},
  remove:async(paths:string[])=>{removes(name,paths);for(const path of paths)objects.delete(`${name}/${path}`);return {error:null};}
};}
async function upload(){await uploadMedia(c.db,actor,image,'../fixture-upload.webp','Een dartbord','image/webp');return (await c.db.select().from(s.media).where(eq(s.media.bucket,'private-media')))[0];}
function failTransactionAfterWrites(){const original=c.db.transaction.bind(c.db);vi.spyOn(c.db,'transaction').mockImplementationOnce(callback=>original(async tx=>{await callback(tx);throw new Error('Fixture database failure');}));}
beforeAll(async()=>{c=await testDatabase();actor=crypto.randomUUID();await c.db.insert(s.users).values({id:actor,name:'Media admin',email:'media-admin@example.invalid'});image=await sharp({create:{width:48,height:24,channels:3,background:'#2563eb'}}).webp().toBuffer();});
afterAll(async()=>{await c?.client.close();});
beforeEach(async()=>{for(const [key,value]of Object.entries({APP_ENV:'development',APP_URL:'http://localhost:3000',DATABASE_MODE:'local',SYNC_ENABLED:'false',SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_SECRET_KEY:'fixture-storage-key'}))vi.stubEnv(key,value);vi.stubEnv('VERCEL',undefined);objects.clear();writes.mockClear();removes.mockClear();storage.from.mockReset().mockImplementation(bucket);await c.db.delete(s.media).where(eq(s.media.bucket,'private-media'));});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
describe('Server-only validated images and Storage compensation',()=>{
  it('valid WebP is private by default with a safe name, unique path, database link and audit',async()=>{const row=await upload();expect(row).toMatchObject({status:'private',mimeType:'image/webp',width:48,height:24,uploadedBy:actor,filename:'fixture-upload.webp'});expect(row.storagePath).toMatch(/^uploads\/[0-9a-f-]+\.webp$/);expect(objects.has(`private-media/${row.storagePath}`)).toBe(true);expect(objects.has(`published-media/${row.storagePath}`)).toBe(false);expect(writes).toHaveBeenCalledWith('private-media',row.storagePath,{contentType:'image/webp',upsert:false});expect((await c.db.select().from(s.auditLogs).where(eq(s.auditLogs.entityId,row.id)))[0].action).toBe('media.upload');});
  it('rejects anonymous/unregistered writers before Storage',async()=>{await expect(uploadMedia(c.db,crypto.randomUUID(),image,'x.webp','Test')).rejects.toMatchObject({status:403});expect(storage.from).not.toHaveBeenCalled();});
  it('rejects an editor before publishing or uploading',async()=>{const id=crypto.randomUUID();await c.db.insert(s.users).values({id,name:'Editor',email:`${id}@example.invalid`,role:'editor'});await expect(uploadMedia(c.db,id,image,'x.webp','Test')).rejects.toMatchObject({status:403});expect(writes).not.toHaveBeenCalled();});
  it('requires descriptive alt text',async()=>{await expect(uploadMedia(c.db,actor,image,'x.webp',' ')).rejects.toMatchObject({status:400});expect(writes).not.toHaveBeenCalled();});
  it('rejects MIME/content mismatch',async()=>{await expect(prepareImage(image,'image/png')).rejects.toMatchObject({status:400});});
  it('removes path traversal, markup and file extensions from display filenames',()=>{expect(safeImageFilename('..\\folder/<script>.png')).toBe('script.webp');expect(safeImageFilename('../../')).toBe('afbeelding.webp');});
  it('publishes a WebP copy, preserves the private original and links published status',async()=>{const row=await upload();await changeMedia(c.db,actor,row.id,'published','Publiek dartbord');expect(objects.has(`published-media/${row.storagePath}`)).toBe(true);expect(objects.has(`private-media/${row.storagePath}`)).toBe(true);expect((await c.db.select().from(s.media).where(eq(s.media.id,row.id)))[0].status).toBe('published');});
  it('editing published metadata never overwrites an existing public file',async()=>{const row=await upload();await changeMedia(c.db,actor,row.id,'published','Test');writes.mockClear();await changeMedia(c.db,actor,row.id,'published','Andere tekst');expect(writes).not.toHaveBeenCalled();});
  it('withdrawing publication removes only the public copy',async()=>{const row=await upload();await changeMedia(c.db,actor,row.id,'published','Test');await changeMedia(c.db,actor,row.id,'private','Test');expect(objects.has(`published-media/${row.storagePath}`)).toBe(false);expect(objects.has(`private-media/${row.storagePath}`)).toBe(true);expect((await c.db.select().from(s.media).where(eq(s.media.id,row.id)))[0].status).toBe('private');});
  it('archiving retains private original and removes public access',async()=>{const row=await upload();await changeMedia(c.db,actor,row.id,'published','Test');await changeMedia(c.db,actor,row.id,'archived','Test');expect(objects.has(`published-media/${row.storagePath}`)).toBe(false);expect(objects.has(`private-media/${row.storagePath}`)).toBe(true);expect((await c.db.select().from(s.media).where(eq(s.media.id,row.id)))[0].status).toBe('archived');});
  it('failed database write rolls back record and audit and cleans the private upload',async()=>{failTransactionAfterWrites();await expect(upload()).rejects.toThrow('opgeruimd');expect(objects.size).toBe(0);expect(await c.db.select().from(s.media).where(eq(s.media.bucket,'private-media'))).toHaveLength(0);});
  it('failed publication transaction removes the new public copy and keeps private DB status',async()=>{const row=await upload();failTransactionAfterWrites();await expect(changeMedia(c.db,actor,row.id,'published','Test')).rejects.toMatchObject({status:502});expect(objects.has(`published-media/${row.storagePath}`)).toBe(false);expect(objects.has(`private-media/${row.storagePath}`)).toBe(true);expect((await c.db.select().from(s.media).where(eq(s.media.id,row.id)))[0].status).toBe('private');});
  it('failed withdrawal restores exact public bytes and original published database status',async()=>{const row=await upload();await changeMedia(c.db,actor,row.id,'published','Test');const original=objects.get(`published-media/${row.storagePath}`);failTransactionAfterWrites();await expect(changeMedia(c.db,actor,row.id,'private','Test')).rejects.toMatchObject({status:502});expect(objects.get(`published-media/${row.storagePath}`)).toEqual(original);expect((await c.db.select().from(s.media).where(eq(s.media.id,row.id)))[0].status).toBe('published');});
  it('cleanup failure explicitly requests a Storage check and does not falsely report success',async()=>{failTransactionAfterWrites();storage.from.mockImplementation(name=>({...bucket(name),remove:async()=>({error:{message:'fixture-remove-failed'}})}));await expect(upload()).rejects.toThrow('Controleer Storage');});
  it('storage upload error leaves no new DB row',async()=>{storage.from.mockImplementation(name=>({...bucket(name),upload:async()=>({error:{message:'fixture-upload-failed'}})}));await expect(upload()).rejects.toMatchObject({status:502});expect(await c.db.select().from(s.media).where(eq(s.media.bucket,'private-media'))).toHaveLength(0);});
  it('missing private original cannot become a public image',async()=>{const row=await upload();objects.clear();await expect(changeMedia(c.db,actor,row.id,'published','Test')).rejects.toMatchObject({status:502});expect((await c.db.select().from(s.media).where(eq(s.media.id,row.id)))[0].status).toBe('private');});
});
