import type {getAdminData} from '@/lib/queries';
import {AdminForm, AdminCancelButton, type ArchiveConfirmation} from './admin-form';
import {recordRevision} from '@/lib/admin/record-guard';
type AdminData=Awaited<ReturnType<typeof getAdminData>>;
export function Field({name,label,value='',type='text',required=false}:{name:string;label:string;value?:string|number|null;type?:string;required?:boolean}){return <label>{label}<input name={name} type={type} defaultValue={value??''} required={required}/></label>;}
export function TextField({name,label,value='',rows=4}:{name:string;label:string;value?:string|null;rows?:number}){return <label>{label}<textarea name={name} defaultValue={value??''} rows={rows}/></label>;}
export function EditForm({resource,id,children,disabled=false,expectedRevision,archiveConfirmation}:{resource:string;id?:string;children:React.ReactNode;disabled?:boolean;expectedRevision?:string;archiveConfirmation?:ArchiveConfirmation}){return <AdminForm action={`/api/admin/${resource}`} disabled={disabled} archiveConfirmation={archiveConfirmation}>{id&&<input type="hidden" name="id" value={id}/>}<input type="hidden" name="action" value="save"/>{expectedRevision&&<input type="hidden" name="expectedRevision" value={expectedRevision}/>}{children}<div className="editor-buttons"><button className="button small" disabled={disabled}>Opslaan</button><AdminCancelButton/></div></AdminForm>;}
export function PlayerEditor({player,media=[]}:{media?:AdminData['media'];player?:AdminData['allPlayers'][number]}){return <EditForm resource="spelers" id={player?.id} expectedRevision={player?recordRevision(player):undefined} archiveConfirmation={player?.isActive?{field:'isActive',name:player.displayName}:undefined}><Field name="displayName" label="Profielnaam" value={player?.displayName} required/><div className="two-col"><Field name="firstName" label="Voornaam" value={player?.firstName} required/><Field name="lastName" label="Achternaam" value={player?.lastName} required/></div><label>Profielfoto<select name="photoMediaId" defaultValue={player?.photoMediaId??''}><option value="">Geen</option>{media.filter(m=>m.status==='published').map(m=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></label><Field name="nickname" label="Bijnaam" value={player?.nickname}/><TextField name="bio" label="Biografie" value={player?.bio}/><Field name="sortOrder" label="Volgorde" type="number" value={player?.sortOrder??0}/><label><input type="checkbox" name="isActive" defaultChecked={player?.isActive??true}/> Zichtbaar profiel</label></EditForm>;}
const date=(d:Date|null|undefined)=>d?.toISOString()??'';
export function NewsEditor({post,media}:{post?:AdminData['posts'][number];media:AdminData['media']}){return <EditForm resource="nieuws" id={post?.id} expectedRevision={post?recordRevision(post):undefined} archiveConfirmation={post&&post.status!=='archived'?{field:'status',name:post.title}:undefined}><Field name="title" label="Titel" value={post?.title} required/><Field name="slug" label="URL-naam (optioneel)" value={post?.slug}/><Field name="category" label="Categorie" value={post?.category??'Teamnieuws'} required/><TextField name="excerpt" label="Samenvatting" value={post?.excerpt}/><TextField name="content" label="Bericht (eenvoudige HTML toegestaan)" value={post?.content} rows={10}/><label>Status<select name="status" defaultValue={post?.status??'draft'}><option value="draft">Concept</option><option value="published">Gepubliceerd</option><option value="archived">Gearchiveerd</option></select></label><Field name="publishedAt" label="Publicatie (ISO-datum, tijdzone verplicht; leeg = nu)" value={date(post?.publishedAt)}/><label>Afbeelding<select name="featuredMediaId" defaultValue={post?.featuredMediaId??''}><option value="">Geen</option>{media.filter(m=>m.status==='published').map(m=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></label></EditForm>;}
export function EventEditor({event}:{event?:AdminData['events'][number]}){return <EditForm resource="agenda" id={event?.id} expectedRevision={event?recordRevision(event):undefined}><Field name="title" label="Titel" value={event?.title} required/><TextField name="description" label="Omschrijving" value={event?.description}/><Field name="startsAt" label="Begin (ISO-datum met tijdzone, bijvoorbeeld 2026-10-15T20:00:00+02:00)" value={date(event?.startsAt)} required/><Field name="endsAt" label="Einde (optioneel, met tijdzone)" value={date(event?.endsAt)}/><Field name="location" label="Locatie" value={event?.location}/><label>Soort<select name="eventType" defaultValue={event?.eventType??'team_event'}>{[['team_event','Teamactiviteit'],['training','Training'],['tournament','Toernooi'],['other','Overig']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></EditForm>;}
export function SponsorEditor({sponsor,media}:{sponsor?:AdminData['sponsors'][number];media:AdminData['media']}){return <EditForm resource="sponsors" id={sponsor?.id} expectedRevision={sponsor?recordRevision(sponsor):undefined} archiveConfirmation={sponsor?.isActive?{field:'isActive',name:sponsor.name}:undefined}><Field name="name" label="Naam" value={sponsor?.name} required/><Field name="websiteUrl" label="Website" value={sponsor?.websiteUrl} type="url"/><TextField name="description" label="Omschrijving" value={sponsor?.description}/><Field name="sortOrder" label="Volgorde" type="number" value={sponsor?.sortOrder??0}/><label>Logo<select name="logoMediaId" defaultValue={sponsor?.logoMediaId??''}><option value="">Geen</option>{media.filter(m=>m.status==='published').map(m=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></label><label><input type="checkbox" name="isActive" defaultChecked={sponsor?.isActive??true}/> Actief</label></EditForm>;}
export function CorrectionForm({resource,targets,fields}:{resource:string;targets:{id:string;name:string}[];fields:{value:string;name:string}[]}){return <EditForm resource={resource}><label>Gegeven<select name="targetId" required>{targets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Veld<select name="fieldName" required>{fields.map(f=><option key={f.value} value={f.value}>{f.name}</option>)}</select></label><Field name="value" label="Gecorrigeerde waarde" required/><TextField name="reason" label="Reden (minimaal 5 tekens)"/><p className="muted">Deze correctie blijft apart van Bullshooter opgeslagen. De oorspronkelijke bronwaarde blijft bewaard.</p></EditForm>;}
