import Link from 'next/link';
import Image from 'next/image';
import {publicMediaUrl} from '@/lib/media';
import {ArrowUpRight,CalendarDays,MapPin,ChevronRight} from 'lucide-react';
import type {SiteData} from '@/lib/queries';
export function dateNL(value:string|Date|null|undefined,full=false){if(!value)return 'Datum onbekend';const d=typeof value==='string'?new Date(value.length===10?`${value}T12:00:00+02:00`:value):value;return new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:full?'long':'short',year:full?'numeric':undefined,timeZone:'Europe/Amsterdam'}).format(d);}
export function reportDateNL(value:Date|undefined){return value?new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(value):'Nog geen report';}
export function ContextSelect({data,path}:{data:Pick<SiteData,'context'|'contexts'>;path:string}){return <form action={path} className="context-select"><label htmlFor="context">Competitie & seizoen</label><div><select name="context" id="context" defaultValue={data.context.id}>{data.contexts.map(c=><option key={c.id} value={c.id}>{c.competition} · {c.season} · {c.division}</option>)}</select><button className="button secondary small">Tonen</button></div></form>;}
export function SourceNote({data}:{data:SiteData}){return <p className="source-note">{data.context.competitionSlug==='nsjl-zomer'?'Bron: originele NSJL-website · historische momentopname':'Bron: Bullshooter Events'}{data.report&&<> · Report {reportDateNL(data.report.reportDatetimeLocal)}</>}{data.lastSync?.finishedAt&&<> · Laatste geslaagde controle {dateNL(data.lastSync.finishedAt,true)}</>}</p>;}
export function StandTable({data,compact=false}:{data:SiteData;compact?:boolean}){return <div className="standing-table"><div className="stand-head"><span>#</span><span>TEAM</span><span>G</span><span>W</span><span>L</span><span>WIN %</span></div>{(compact?data.standings.slice(0,9):data.standings).map(t=><div key={t.id} className={`stand-row ${t.isNsjl?'our-row':''}`}><span className="position">{t.position??'—'}</span><strong>{t.name}{t.isNsjl&&<small className="team-badge">WIJ</small>}</strong><span>{t.games}</span><span>{t.wins}</span><span>{t.losses??'—'}</span><strong className={t.isNsjl?'lime':''}>{Number(t.winPercentage).toLocaleString('nl-NL',{maximumFractionDigits:1})}%</strong></div>)}{!data.standings.length&&<p className="empty">Nog geen bevestigde stand.</p>}</div>;}
type Match=SiteData['matches'][number];
export function MatchCard({match,label}:{match:Match|undefined;label?:string}){return <div className="match-card">{label&&<div className="match-label"><CalendarDays size={15}/><span>{label}</span></div>}{match?<><div className="match-meta"><span>{dateNL(match.playedDate||match.scheduledDate,true)}</span><span>WEEK {match.week??'—'}</span></div><div className="match-teams"><strong className={match.homeNsjl?'lime':''}>{match.homeNsjl?'NSJL':match.homeName}</strong><span className="match-score">{match.status==='completed'?`${match.homeScore} – ${match.awayScore}`:'VS'}</span><strong className={match.awayNsjl?'lime':''}>{match.awayNsjl?'NSJL':match.awayName}</strong></div><div className="match-bottom"><span><MapPin size={14}/>{match.venue||'Locatie volgt'}{match.startTime&&` · ${match.startTime.slice(0,5)}`}</span><Link href={`/wedstrijden/${match.slug}`} aria-label={`Details ${match.homeName} tegen ${match.awayName}`}><ArrowUpRight size={18}/></Link></div>{match.status==='postponed'&&<small className="amber">Schema gewijzigd / verplaatst</small>}</>:<p className="empty">Nog geen bevestigde wedstrijd beschikbaar.</p>}</div>;}
export function ProfileCards({data}:{data:SiteData}){return <div className="profile-grid">{data.profiles.map((p,i)=>{const stats=data.stats.find(v=>v.stats.playerId===p.id)?.stats;const photo=data.media.find(m=>m.id===p.photoMediaId);return <Link href={`/spelers/${p.slug}?context=${data.context.id}`} className="profile-card" key={p.id}><span className="profile-number">0{i+1}</span><div className="avatar">{photo?<Image unoptimized src={publicMediaUrl(photo.id)} alt={photo.altText} width={140} height={140}/>:<>{p.firstName[0]}{p.lastName.replace(/^van (de |den )?/,'')[0]}</>}</div><div className="profile-name"><h3>{p.displayName}</h3><ArrowUpRight size={18}/></div><p>{p.nickname||'No skill. Just luck.'}</p><div className="profile-stats"><div><strong>{stats?.x01Ppd??'—'}</strong><span>PPD</span></div><div><strong>{stats?.cricketMpr??'—'}</strong><span>MPR</span></div><div><strong>{stats?.x01Wins??'—'}</strong><span>X01 WINS</span></div></div>{!stats&&<small>Geen gekoppelde NSJL-statistieken in dit seizoen.</small>}</Link>;})}</div>;}
export function NewsCards({data}:{data:SiteData}){return <div className="news-grid">{data.news.map((n,i)=><Link className="news-card" key={n.id} href={`/nieuws/${n.slug}`}><div className={`news-art art-${i%3}`}>{data.media.find(m=>m.id===n.featuredMediaId)?<Image unoptimized src={publicMediaUrl(data.media.find(m=>m.id===n.featuredMediaId)!.id)} alt={data.media.find(m=>m.id===n.featuredMediaId)!.altText} width={720} height={400}/>:<span>{['09 / 01','69.','TIME OUT'][i%3]}</span>}<ArrowUpRight size={22}/></div><div className="news-content"><div className="news-meta"><span>{n.category}</span><span>{dateNL(n.publishedAt)}</span></div><h3>{n.title}</h3><p>{n.excerpt}</p><span className="text-link">Lees het verhaal <ChevronRight size={15}/></span></div></Link>)}</div>;}
export function SectionHead({eyebrow,title,href,linkLabel}:{eyebrow:string;title:string;href?:string;linkLabel?:string}){return <div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{href&&<Link className="text-link" href={href}>{linkLabel||'Bekijk alles'} <ArrowUpRight size={16}/></Link>}</div>;}
